/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using DocuSign.Core.Client;
using DocuSign.Core.Model;

namespace DocuSign.Core.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEnvelopeBulkRecipientsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Deletes the bulk recipient file from an envelope.
        /// </summary>
        /// <remarks>
        /// Deletes the bulk recipient file from an envelope. This cannot be used if the envelope has been sent.  After using this, the &#x60;bulkRecipientsUri&#x60; property is not returned in subsequent GET calls for the envelope, but the recipient will remain as a bulk recipient.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <returns>BulkRecipientsUpdateResponse</returns>
        BulkRecipientsUpdateResponse RecipientsDeleteBulkRecipientsFile (string accountId, string envelopeId, string recipientId);

        /// <summary>
        /// Deletes the bulk recipient file from an envelope.
        /// </summary>
        /// <remarks>
        /// Deletes the bulk recipient file from an envelope. This cannot be used if the envelope has been sent.  After using this, the &#x60;bulkRecipientsUri&#x60; property is not returned in subsequent GET calls for the envelope, but the recipient will remain as a bulk recipient.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <returns>ApiResponse of BulkRecipientsUpdateResponse</returns>
        ApiResponse<BulkRecipientsUpdateResponse> RecipientsDeleteBulkRecipientsFileWithHttpInfo (string accountId, string envelopeId, string recipientId);
        /// <summary>
        /// Gets the bulk recipient file from an envelope.
        /// </summary>
        /// <remarks>
        /// Retrieves the bulk recipient file information from an envelope that has a bulk recipient.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="includeTabs">If **true** include the tabs in the the result.  (optional)</param>
        /// <param name="startPosition">Reserved for DocuSign.  (optional)</param>
        /// <returns>EnvelopeBulkRecipients</returns>
        EnvelopeBulkRecipients RecipientsGetBulkRecipients (string accountId, string envelopeId, string recipientId, string includeTabs = null, string startPosition = null);

        /// <summary>
        /// Gets the bulk recipient file from an envelope.
        /// </summary>
        /// <remarks>
        /// Retrieves the bulk recipient file information from an envelope that has a bulk recipient.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="includeTabs">If **true** include the tabs in the the result.  (optional)</param>
        /// <param name="startPosition">Reserved for DocuSign.  (optional)</param>
        /// <returns>ApiResponse of EnvelopeBulkRecipients</returns>
        ApiResponse<EnvelopeBulkRecipients> RecipientsGetBulkRecipientsWithHttpInfo (string accountId, string envelopeId, string recipientId, string includeTabs = null, string startPosition = null);
        /// <summary>
        /// Adds or replaces envelope bulk recipients.
        /// </summary>
        /// <remarks>
        /// Updates the bulk recipients in a draft envelope using a file upload. The Content-Type supported for uploading a bulk recipient file is CSV (text/csv).  The REST API does not support modifying individual rows or values in the bulk recipients file. It only allows the entire file to be added or replaced with a new file.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="bulkRecipientsRequest"> (optional)</param>
        /// <returns>BulkRecipientsSummaryResponse</returns>
        BulkRecipientsSummaryResponse RecipientsPutBulkRecipients (string accountId, string envelopeId, string recipientId, BulkRecipientsRequest bulkRecipientsRequest = null);

        /// <summary>
        /// Adds or replaces envelope bulk recipients.
        /// </summary>
        /// <remarks>
        /// Updates the bulk recipients in a draft envelope using a file upload. The Content-Type supported for uploading a bulk recipient file is CSV (text/csv).  The REST API does not support modifying individual rows or values in the bulk recipients file. It only allows the entire file to be added or replaced with a new file.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="bulkRecipientsRequest"> (optional)</param>
        /// <returns>ApiResponse of BulkRecipientsSummaryResponse</returns>
        ApiResponse<BulkRecipientsSummaryResponse> RecipientsPutBulkRecipientsWithHttpInfo (string accountId, string envelopeId, string recipientId, BulkRecipientsRequest bulkRecipientsRequest = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Deletes the bulk recipient file from an envelope.
        /// </summary>
        /// <remarks>
        /// Deletes the bulk recipient file from an envelope. This cannot be used if the envelope has been sent.  After using this, the &#x60;bulkRecipientsUri&#x60; property is not returned in subsequent GET calls for the envelope, but the recipient will remain as a bulk recipient.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <returns>Task of BulkRecipientsUpdateResponse</returns>
        System.Threading.Tasks.Task<BulkRecipientsUpdateResponse> RecipientsDeleteBulkRecipientsFileAsync (string accountId, string envelopeId, string recipientId);

        /// <summary>
        /// Deletes the bulk recipient file from an envelope.
        /// </summary>
        /// <remarks>
        /// Deletes the bulk recipient file from an envelope. This cannot be used if the envelope has been sent.  After using this, the &#x60;bulkRecipientsUri&#x60; property is not returned in subsequent GET calls for the envelope, but the recipient will remain as a bulk recipient.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <returns>Task of ApiResponse (BulkRecipientsUpdateResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BulkRecipientsUpdateResponse>> RecipientsDeleteBulkRecipientsFileAsyncWithHttpInfo (string accountId, string envelopeId, string recipientId);
        /// <summary>
        /// Gets the bulk recipient file from an envelope.
        /// </summary>
        /// <remarks>
        /// Retrieves the bulk recipient file information from an envelope that has a bulk recipient.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="includeTabs">If **true** include the tabs in the the result.  (optional)</param>
        /// <param name="startPosition">Reserved for DocuSign.  (optional)</param>
        /// <returns>Task of EnvelopeBulkRecipients</returns>
        System.Threading.Tasks.Task<EnvelopeBulkRecipients> RecipientsGetBulkRecipientsAsync (string accountId, string envelopeId, string recipientId, string includeTabs = null, string startPosition = null);

        /// <summary>
        /// Gets the bulk recipient file from an envelope.
        /// </summary>
        /// <remarks>
        /// Retrieves the bulk recipient file information from an envelope that has a bulk recipient.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="includeTabs">If **true** include the tabs in the the result.  (optional)</param>
        /// <param name="startPosition">Reserved for DocuSign.  (optional)</param>
        /// <returns>Task of ApiResponse (EnvelopeBulkRecipients)</returns>
        System.Threading.Tasks.Task<ApiResponse<EnvelopeBulkRecipients>> RecipientsGetBulkRecipientsAsyncWithHttpInfo (string accountId, string envelopeId, string recipientId, string includeTabs = null, string startPosition = null);
        /// <summary>
        /// Adds or replaces envelope bulk recipients.
        /// </summary>
        /// <remarks>
        /// Updates the bulk recipients in a draft envelope using a file upload. The Content-Type supported for uploading a bulk recipient file is CSV (text/csv).  The REST API does not support modifying individual rows or values in the bulk recipients file. It only allows the entire file to be added or replaced with a new file.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="bulkRecipientsRequest"> (optional)</param>
        /// <returns>Task of BulkRecipientsSummaryResponse</returns>
        System.Threading.Tasks.Task<BulkRecipientsSummaryResponse> RecipientsPutBulkRecipientsAsync (string accountId, string envelopeId, string recipientId, BulkRecipientsRequest bulkRecipientsRequest = null);

        /// <summary>
        /// Adds or replaces envelope bulk recipients.
        /// </summary>
        /// <remarks>
        /// Updates the bulk recipients in a draft envelope using a file upload. The Content-Type supported for uploading a bulk recipient file is CSV (text/csv).  The REST API does not support modifying individual rows or values in the bulk recipients file. It only allows the entire file to be added or replaced with a new file.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="bulkRecipientsRequest"> (optional)</param>
        /// <returns>Task of ApiResponse (BulkRecipientsSummaryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BulkRecipientsSummaryResponse>> RecipientsPutBulkRecipientsAsyncWithHttpInfo (string accountId, string envelopeId, string recipientId, BulkRecipientsRequest bulkRecipientsRequest = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EnvelopeBulkRecipientsApi : IEnvelopeBulkRecipientsApi
    {
        private DocuSign.Core.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EnvelopeBulkRecipientsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EnvelopeBulkRecipientsApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = DocuSign.Core.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EnvelopeBulkRecipientsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EnvelopeBulkRecipientsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = DocuSign.Core.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public DocuSign.Core.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Deletes the bulk recipient file from an envelope. Deletes the bulk recipient file from an envelope. This cannot be used if the envelope has been sent.  After using this, the &#x60;bulkRecipientsUri&#x60; property is not returned in subsequent GET calls for the envelope, but the recipient will remain as a bulk recipient.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <returns>BulkRecipientsUpdateResponse</returns>
        public BulkRecipientsUpdateResponse RecipientsDeleteBulkRecipientsFile (string accountId, string envelopeId, string recipientId)
        {
             ApiResponse<BulkRecipientsUpdateResponse> localVarResponse = RecipientsDeleteBulkRecipientsFileWithHttpInfo(accountId, envelopeId, recipientId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Deletes the bulk recipient file from an envelope. Deletes the bulk recipient file from an envelope. This cannot be used if the envelope has been sent.  After using this, the &#x60;bulkRecipientsUri&#x60; property is not returned in subsequent GET calls for the envelope, but the recipient will remain as a bulk recipient.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <returns>ApiResponse of BulkRecipientsUpdateResponse</returns>
        public ApiResponse< BulkRecipientsUpdateResponse > RecipientsDeleteBulkRecipientsFileWithHttpInfo (string accountId, string envelopeId, string recipientId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling EnvelopeBulkRecipientsApi->RecipientsDeleteBulkRecipientsFile");
            // verify the required parameter 'envelopeId' is set
            if (envelopeId == null)
                throw new ApiException(400, "Missing required parameter 'envelopeId' when calling EnvelopeBulkRecipientsApi->RecipientsDeleteBulkRecipientsFile");
            // verify the required parameter 'recipientId' is set
            if (recipientId == null)
                throw new ApiException(400, "Missing required parameter 'recipientId' when calling EnvelopeBulkRecipientsApi->RecipientsDeleteBulkRecipientsFile");

            var localVarPath = "/v2/accounts/{accountId}/envelopes/{envelopeId}/recipients/{recipientId}/bulk_recipients";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (envelopeId != null) localVarPathParams.Add("envelopeId", Configuration.ApiClient.ParameterToString(envelopeId)); // path parameter
            if (recipientId != null) localVarPathParams.Add("recipientId", Configuration.ApiClient.ParameterToString(recipientId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RecipientsDeleteBulkRecipientsFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BulkRecipientsUpdateResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BulkRecipientsUpdateResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(BulkRecipientsUpdateResponse)));
            
        }

        /// <summary>
        /// Deletes the bulk recipient file from an envelope. Deletes the bulk recipient file from an envelope. This cannot be used if the envelope has been sent.  After using this, the &#x60;bulkRecipientsUri&#x60; property is not returned in subsequent GET calls for the envelope, but the recipient will remain as a bulk recipient.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <returns>Task of BulkRecipientsUpdateResponse</returns>
        public async System.Threading.Tasks.Task<BulkRecipientsUpdateResponse> RecipientsDeleteBulkRecipientsFileAsync (string accountId, string envelopeId, string recipientId)
        {
             ApiResponse<BulkRecipientsUpdateResponse> localVarResponse = await RecipientsDeleteBulkRecipientsFileAsyncWithHttpInfo(accountId, envelopeId, recipientId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Deletes the bulk recipient file from an envelope. Deletes the bulk recipient file from an envelope. This cannot be used if the envelope has been sent.  After using this, the &#x60;bulkRecipientsUri&#x60; property is not returned in subsequent GET calls for the envelope, but the recipient will remain as a bulk recipient.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <returns>Task of ApiResponse (BulkRecipientsUpdateResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BulkRecipientsUpdateResponse>> RecipientsDeleteBulkRecipientsFileAsyncWithHttpInfo (string accountId, string envelopeId, string recipientId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling EnvelopeBulkRecipientsApi->RecipientsDeleteBulkRecipientsFile");
            // verify the required parameter 'envelopeId' is set
            if (envelopeId == null)
                throw new ApiException(400, "Missing required parameter 'envelopeId' when calling EnvelopeBulkRecipientsApi->RecipientsDeleteBulkRecipientsFile");
            // verify the required parameter 'recipientId' is set
            if (recipientId == null)
                throw new ApiException(400, "Missing required parameter 'recipientId' when calling EnvelopeBulkRecipientsApi->RecipientsDeleteBulkRecipientsFile");

            var localVarPath = "/v2/accounts/{accountId}/envelopes/{envelopeId}/recipients/{recipientId}/bulk_recipients";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (envelopeId != null) localVarPathParams.Add("envelopeId", Configuration.ApiClient.ParameterToString(envelopeId)); // path parameter
            if (recipientId != null) localVarPathParams.Add("recipientId", Configuration.ApiClient.ParameterToString(recipientId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RecipientsDeleteBulkRecipientsFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BulkRecipientsUpdateResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BulkRecipientsUpdateResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(BulkRecipientsUpdateResponse)));
            
        }

        /// <summary>
        /// Gets the bulk recipient file from an envelope. Retrieves the bulk recipient file information from an envelope that has a bulk recipient.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="includeTabs">If **true** include the tabs in the the result.  (optional)</param>
        /// <param name="startPosition">Reserved for DocuSign.  (optional)</param>
        /// <returns>EnvelopeBulkRecipients</returns>
        public EnvelopeBulkRecipients RecipientsGetBulkRecipients (string accountId, string envelopeId, string recipientId, string includeTabs = null, string startPosition = null)
        {
             ApiResponse<EnvelopeBulkRecipients> localVarResponse = RecipientsGetBulkRecipientsWithHttpInfo(accountId, envelopeId, recipientId, includeTabs, startPosition);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the bulk recipient file from an envelope. Retrieves the bulk recipient file information from an envelope that has a bulk recipient.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="includeTabs">If **true** include the tabs in the the result.  (optional)</param>
        /// <param name="startPosition">Reserved for DocuSign.  (optional)</param>
        /// <returns>ApiResponse of EnvelopeBulkRecipients</returns>
        public ApiResponse< EnvelopeBulkRecipients > RecipientsGetBulkRecipientsWithHttpInfo (string accountId, string envelopeId, string recipientId, string includeTabs = null, string startPosition = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling EnvelopeBulkRecipientsApi->RecipientsGetBulkRecipients");
            // verify the required parameter 'envelopeId' is set
            if (envelopeId == null)
                throw new ApiException(400, "Missing required parameter 'envelopeId' when calling EnvelopeBulkRecipientsApi->RecipientsGetBulkRecipients");
            // verify the required parameter 'recipientId' is set
            if (recipientId == null)
                throw new ApiException(400, "Missing required parameter 'recipientId' when calling EnvelopeBulkRecipientsApi->RecipientsGetBulkRecipients");

            var localVarPath = "/v2/accounts/{accountId}/envelopes/{envelopeId}/recipients/{recipientId}/bulk_recipients";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (envelopeId != null) localVarPathParams.Add("envelopeId", Configuration.ApiClient.ParameterToString(envelopeId)); // path parameter
            if (recipientId != null) localVarPathParams.Add("recipientId", Configuration.ApiClient.ParameterToString(recipientId)); // path parameter
            if (includeTabs != null) localVarQueryParams.Add("include_tabs", Configuration.ApiClient.ParameterToString(includeTabs)); // query parameter
            if (startPosition != null) localVarQueryParams.Add("start_position", Configuration.ApiClient.ParameterToString(startPosition)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RecipientsGetBulkRecipients", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EnvelopeBulkRecipients>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (EnvelopeBulkRecipients) Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvelopeBulkRecipients)));
            
        }

        /// <summary>
        /// Gets the bulk recipient file from an envelope. Retrieves the bulk recipient file information from an envelope that has a bulk recipient.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="includeTabs">If **true** include the tabs in the the result.  (optional)</param>
        /// <param name="startPosition">Reserved for DocuSign.  (optional)</param>
        /// <returns>Task of EnvelopeBulkRecipients</returns>
        public async System.Threading.Tasks.Task<EnvelopeBulkRecipients> RecipientsGetBulkRecipientsAsync (string accountId, string envelopeId, string recipientId, string includeTabs = null, string startPosition = null)
        {
             ApiResponse<EnvelopeBulkRecipients> localVarResponse = await RecipientsGetBulkRecipientsAsyncWithHttpInfo(accountId, envelopeId, recipientId, includeTabs, startPosition);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets the bulk recipient file from an envelope. Retrieves the bulk recipient file information from an envelope that has a bulk recipient.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="includeTabs">If **true** include the tabs in the the result.  (optional)</param>
        /// <param name="startPosition">Reserved for DocuSign.  (optional)</param>
        /// <returns>Task of ApiResponse (EnvelopeBulkRecipients)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<EnvelopeBulkRecipients>> RecipientsGetBulkRecipientsAsyncWithHttpInfo (string accountId, string envelopeId, string recipientId, string includeTabs = null, string startPosition = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling EnvelopeBulkRecipientsApi->RecipientsGetBulkRecipients");
            // verify the required parameter 'envelopeId' is set
            if (envelopeId == null)
                throw new ApiException(400, "Missing required parameter 'envelopeId' when calling EnvelopeBulkRecipientsApi->RecipientsGetBulkRecipients");
            // verify the required parameter 'recipientId' is set
            if (recipientId == null)
                throw new ApiException(400, "Missing required parameter 'recipientId' when calling EnvelopeBulkRecipientsApi->RecipientsGetBulkRecipients");

            var localVarPath = "/v2/accounts/{accountId}/envelopes/{envelopeId}/recipients/{recipientId}/bulk_recipients";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (envelopeId != null) localVarPathParams.Add("envelopeId", Configuration.ApiClient.ParameterToString(envelopeId)); // path parameter
            if (recipientId != null) localVarPathParams.Add("recipientId", Configuration.ApiClient.ParameterToString(recipientId)); // path parameter
            if (includeTabs != null) localVarQueryParams.Add("include_tabs", Configuration.ApiClient.ParameterToString(includeTabs)); // query parameter
            if (startPosition != null) localVarQueryParams.Add("start_position", Configuration.ApiClient.ParameterToString(startPosition)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RecipientsGetBulkRecipients", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EnvelopeBulkRecipients>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (EnvelopeBulkRecipients) Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvelopeBulkRecipients)));
            
        }

        /// <summary>
        /// Adds or replaces envelope bulk recipients. Updates the bulk recipients in a draft envelope using a file upload. The Content-Type supported for uploading a bulk recipient file is CSV (text/csv).  The REST API does not support modifying individual rows or values in the bulk recipients file. It only allows the entire file to be added or replaced with a new file.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="bulkRecipientsRequest"> (optional)</param>
        /// <returns>BulkRecipientsSummaryResponse</returns>
        public BulkRecipientsSummaryResponse RecipientsPutBulkRecipients (string accountId, string envelopeId, string recipientId, BulkRecipientsRequest bulkRecipientsRequest = null)
        {
             ApiResponse<BulkRecipientsSummaryResponse> localVarResponse = RecipientsPutBulkRecipientsWithHttpInfo(accountId, envelopeId, recipientId, bulkRecipientsRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Adds or replaces envelope bulk recipients. Updates the bulk recipients in a draft envelope using a file upload. The Content-Type supported for uploading a bulk recipient file is CSV (text/csv).  The REST API does not support modifying individual rows or values in the bulk recipients file. It only allows the entire file to be added or replaced with a new file.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="bulkRecipientsRequest"> (optional)</param>
        /// <returns>ApiResponse of BulkRecipientsSummaryResponse</returns>
        public ApiResponse< BulkRecipientsSummaryResponse > RecipientsPutBulkRecipientsWithHttpInfo (string accountId, string envelopeId, string recipientId, BulkRecipientsRequest bulkRecipientsRequest = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling EnvelopeBulkRecipientsApi->RecipientsPutBulkRecipients");
            // verify the required parameter 'envelopeId' is set
            if (envelopeId == null)
                throw new ApiException(400, "Missing required parameter 'envelopeId' when calling EnvelopeBulkRecipientsApi->RecipientsPutBulkRecipients");
            // verify the required parameter 'recipientId' is set
            if (recipientId == null)
                throw new ApiException(400, "Missing required parameter 'recipientId' when calling EnvelopeBulkRecipientsApi->RecipientsPutBulkRecipients");

            var localVarPath = "/v2/accounts/{accountId}/envelopes/{envelopeId}/recipients/{recipientId}/bulk_recipients";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (envelopeId != null) localVarPathParams.Add("envelopeId", Configuration.ApiClient.ParameterToString(envelopeId)); // path parameter
            if (recipientId != null) localVarPathParams.Add("recipientId", Configuration.ApiClient.ParameterToString(recipientId)); // path parameter
            if (bulkRecipientsRequest != null && bulkRecipientsRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(bulkRecipientsRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = bulkRecipientsRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RecipientsPutBulkRecipients", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BulkRecipientsSummaryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BulkRecipientsSummaryResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(BulkRecipientsSummaryResponse)));
            
        }

        /// <summary>
        /// Adds or replaces envelope bulk recipients. Updates the bulk recipients in a draft envelope using a file upload. The Content-Type supported for uploading a bulk recipient file is CSV (text/csv).  The REST API does not support modifying individual rows or values in the bulk recipients file. It only allows the entire file to be added or replaced with a new file.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="bulkRecipientsRequest"> (optional)</param>
        /// <returns>Task of BulkRecipientsSummaryResponse</returns>
        public async System.Threading.Tasks.Task<BulkRecipientsSummaryResponse> RecipientsPutBulkRecipientsAsync (string accountId, string envelopeId, string recipientId, BulkRecipientsRequest bulkRecipientsRequest = null)
        {
             ApiResponse<BulkRecipientsSummaryResponse> localVarResponse = await RecipientsPutBulkRecipientsAsyncWithHttpInfo(accountId, envelopeId, recipientId, bulkRecipientsRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Adds or replaces envelope bulk recipients. Updates the bulk recipients in a draft envelope using a file upload. The Content-Type supported for uploading a bulk recipient file is CSV (text/csv).  The REST API does not support modifying individual rows or values in the bulk recipients file. It only allows the entire file to be added or replaced with a new file.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="envelopeId">The envelope&#39;s GUID. Eg 93be49ab-afa0-4adf-933c-f752070d71ec </param>
        /// <param name="recipientId">The &#x60;recipientId&#x60; used when the envelope or template was created.</param>
        /// <param name="bulkRecipientsRequest"> (optional)</param>
        /// <returns>Task of ApiResponse (BulkRecipientsSummaryResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BulkRecipientsSummaryResponse>> RecipientsPutBulkRecipientsAsyncWithHttpInfo (string accountId, string envelopeId, string recipientId, BulkRecipientsRequest bulkRecipientsRequest = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling EnvelopeBulkRecipientsApi->RecipientsPutBulkRecipients");
            // verify the required parameter 'envelopeId' is set
            if (envelopeId == null)
                throw new ApiException(400, "Missing required parameter 'envelopeId' when calling EnvelopeBulkRecipientsApi->RecipientsPutBulkRecipients");
            // verify the required parameter 'recipientId' is set
            if (recipientId == null)
                throw new ApiException(400, "Missing required parameter 'recipientId' when calling EnvelopeBulkRecipientsApi->RecipientsPutBulkRecipients");

            var localVarPath = "/v2/accounts/{accountId}/envelopes/{envelopeId}/recipients/{recipientId}/bulk_recipients";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (envelopeId != null) localVarPathParams.Add("envelopeId", Configuration.ApiClient.ParameterToString(envelopeId)); // path parameter
            if (recipientId != null) localVarPathParams.Add("recipientId", Configuration.ApiClient.ParameterToString(recipientId)); // path parameter
            if (bulkRecipientsRequest != null && bulkRecipientsRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(bulkRecipientsRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = bulkRecipientsRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RecipientsPutBulkRecipients", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BulkRecipientsSummaryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BulkRecipientsSummaryResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(BulkRecipientsSummaryResponse)));
            
        }

    }
}
