/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using DocuSign.Core.Client;
using DocuSign.Core.Model;

namespace DocuSign.Core.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWorkspacesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete Workspace
        /// </summary>
        /// <remarks>
        /// Deletes an existing workspace (logically).
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Workspaces</returns>
        Workspaces WorkspaceDeleteWorkspace (string accountId, string workspaceId);

        /// <summary>
        /// Delete Workspace
        /// </summary>
        /// <remarks>
        /// Deletes an existing workspace (logically).
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>ApiResponse of Workspaces</returns>
        ApiResponse<Workspaces> WorkspaceDeleteWorkspaceWithHttpInfo (string accountId, string workspaceId);
        /// <summary>
        /// Get Workspace
        /// </summary>
        /// <remarks>
        /// Retrives properties about a workspace given a unique workspaceId. 
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Workspaces</returns>
        Workspaces WorkspaceGetWorkspace (string accountId, string workspaceId);

        /// <summary>
        /// Get Workspace
        /// </summary>
        /// <remarks>
        /// Retrives properties about a workspace given a unique workspaceId. 
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>ApiResponse of Workspaces</returns>
        ApiResponse<Workspaces> WorkspaceGetWorkspaceWithHttpInfo (string accountId, string workspaceId);
        /// <summary>
        /// List Workspaces
        /// </summary>
        /// <remarks>
        /// Gets information about the Workspaces that have been created.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <returns>WorkspaceList</returns>
        WorkspaceList WorkspaceGetWorkspaces (string accountId);

        /// <summary>
        /// List Workspaces
        /// </summary>
        /// <remarks>
        /// Gets information about the Workspaces that have been created.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <returns>ApiResponse of WorkspaceList</returns>
        ApiResponse<WorkspaceList> WorkspaceGetWorkspacesWithHttpInfo (string accountId);
        /// <summary>
        /// Create a Workspace
        /// </summary>
        /// <remarks>
        /// Creates a new workspace.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Workspaces</returns>
        Workspaces WorkspacePostWorkspace (string accountId, Workspaces workspaces = null);

        /// <summary>
        /// Create a Workspace
        /// </summary>
        /// <remarks>
        /// Creates a new workspace.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>ApiResponse of Workspaces</returns>
        ApiResponse<Workspaces> WorkspacePostWorkspaceWithHttpInfo (string accountId, Workspaces workspaces = null);
        /// <summary>
        /// Update Workspace
        /// </summary>
        /// <remarks>
        /// Updates information about a specific workspace.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Workspaces</returns>
        Workspaces WorkspacePutWorkspace (string accountId, string workspaceId, Workspaces workspaces = null);

        /// <summary>
        /// Update Workspace
        /// </summary>
        /// <remarks>
        /// Updates information about a specific workspace.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>ApiResponse of Workspaces</returns>
        ApiResponse<Workspaces> WorkspacePutWorkspaceWithHttpInfo (string accountId, string workspaceId, Workspaces workspaces = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Delete Workspace
        /// </summary>
        /// <remarks>
        /// Deletes an existing workspace (logically).
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Task of Workspaces</returns>
        System.Threading.Tasks.Task<Workspaces> WorkspaceDeleteWorkspaceAsync (string accountId, string workspaceId);

        /// <summary>
        /// Delete Workspace
        /// </summary>
        /// <remarks>
        /// Deletes an existing workspace (logically).
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Task of ApiResponse (Workspaces)</returns>
        System.Threading.Tasks.Task<ApiResponse<Workspaces>> WorkspaceDeleteWorkspaceAsyncWithHttpInfo (string accountId, string workspaceId);
        /// <summary>
        /// Get Workspace
        /// </summary>
        /// <remarks>
        /// Retrives properties about a workspace given a unique workspaceId. 
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Task of Workspaces</returns>
        System.Threading.Tasks.Task<Workspaces> WorkspaceGetWorkspaceAsync (string accountId, string workspaceId);

        /// <summary>
        /// Get Workspace
        /// </summary>
        /// <remarks>
        /// Retrives properties about a workspace given a unique workspaceId. 
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Task of ApiResponse (Workspaces)</returns>
        System.Threading.Tasks.Task<ApiResponse<Workspaces>> WorkspaceGetWorkspaceAsyncWithHttpInfo (string accountId, string workspaceId);
        /// <summary>
        /// List Workspaces
        /// </summary>
        /// <remarks>
        /// Gets information about the Workspaces that have been created.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <returns>Task of WorkspaceList</returns>
        System.Threading.Tasks.Task<WorkspaceList> WorkspaceGetWorkspacesAsync (string accountId);

        /// <summary>
        /// List Workspaces
        /// </summary>
        /// <remarks>
        /// Gets information about the Workspaces that have been created.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <returns>Task of ApiResponse (WorkspaceList)</returns>
        System.Threading.Tasks.Task<ApiResponse<WorkspaceList>> WorkspaceGetWorkspacesAsyncWithHttpInfo (string accountId);
        /// <summary>
        /// Create a Workspace
        /// </summary>
        /// <remarks>
        /// Creates a new workspace.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Task of Workspaces</returns>
        System.Threading.Tasks.Task<Workspaces> WorkspacePostWorkspaceAsync (string accountId, Workspaces workspaces = null);

        /// <summary>
        /// Create a Workspace
        /// </summary>
        /// <remarks>
        /// Creates a new workspace.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Task of ApiResponse (Workspaces)</returns>
        System.Threading.Tasks.Task<ApiResponse<Workspaces>> WorkspacePostWorkspaceAsyncWithHttpInfo (string accountId, Workspaces workspaces = null);
        /// <summary>
        /// Update Workspace
        /// </summary>
        /// <remarks>
        /// Updates information about a specific workspace.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Task of Workspaces</returns>
        System.Threading.Tasks.Task<Workspaces> WorkspacePutWorkspaceAsync (string accountId, string workspaceId, Workspaces workspaces = null);

        /// <summary>
        /// Update Workspace
        /// </summary>
        /// <remarks>
        /// Updates information about a specific workspace.
        /// </remarks>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Task of ApiResponse (Workspaces)</returns>
        System.Threading.Tasks.Task<ApiResponse<Workspaces>> WorkspacePutWorkspaceAsyncWithHttpInfo (string accountId, string workspaceId, Workspaces workspaces = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WorkspacesApi : IWorkspacesApi
    {
        private DocuSign.Core.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspacesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WorkspacesApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = DocuSign.Core.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspacesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WorkspacesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = DocuSign.Core.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public DocuSign.Core.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Delete Workspace Deletes an existing workspace (logically).
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Workspaces</returns>
        public Workspaces WorkspaceDeleteWorkspace (string accountId, string workspaceId)
        {
             ApiResponse<Workspaces> localVarResponse = WorkspaceDeleteWorkspaceWithHttpInfo(accountId, workspaceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Workspace Deletes an existing workspace (logically).
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>ApiResponse of Workspaces</returns>
        public ApiResponse< Workspaces > WorkspaceDeleteWorkspaceWithHttpInfo (string accountId, string workspaceId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling WorkspacesApi->WorkspaceDeleteWorkspace");
            // verify the required parameter 'workspaceId' is set
            if (workspaceId == null)
                throw new ApiException(400, "Missing required parameter 'workspaceId' when calling WorkspacesApi->WorkspaceDeleteWorkspace");

            var localVarPath = "/v2/accounts/{accountId}/workspaces/{workspaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (workspaceId != null) localVarPathParams.Add("workspaceId", Configuration.ApiClient.ParameterToString(workspaceId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceDeleteWorkspace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Workspaces>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Workspaces) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Workspaces)));
            
        }

        /// <summary>
        /// Delete Workspace Deletes an existing workspace (logically).
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Task of Workspaces</returns>
        public async System.Threading.Tasks.Task<Workspaces> WorkspaceDeleteWorkspaceAsync (string accountId, string workspaceId)
        {
             ApiResponse<Workspaces> localVarResponse = await WorkspaceDeleteWorkspaceAsyncWithHttpInfo(accountId, workspaceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete Workspace Deletes an existing workspace (logically).
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Task of ApiResponse (Workspaces)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Workspaces>> WorkspaceDeleteWorkspaceAsyncWithHttpInfo (string accountId, string workspaceId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling WorkspacesApi->WorkspaceDeleteWorkspace");
            // verify the required parameter 'workspaceId' is set
            if (workspaceId == null)
                throw new ApiException(400, "Missing required parameter 'workspaceId' when calling WorkspacesApi->WorkspaceDeleteWorkspace");

            var localVarPath = "/v2/accounts/{accountId}/workspaces/{workspaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (workspaceId != null) localVarPathParams.Add("workspaceId", Configuration.ApiClient.ParameterToString(workspaceId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceDeleteWorkspace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Workspaces>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Workspaces) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Workspaces)));
            
        }

        /// <summary>
        /// Get Workspace Retrives properties about a workspace given a unique workspaceId. 
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Workspaces</returns>
        public Workspaces WorkspaceGetWorkspace (string accountId, string workspaceId)
        {
             ApiResponse<Workspaces> localVarResponse = WorkspaceGetWorkspaceWithHttpInfo(accountId, workspaceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Workspace Retrives properties about a workspace given a unique workspaceId. 
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>ApiResponse of Workspaces</returns>
        public ApiResponse< Workspaces > WorkspaceGetWorkspaceWithHttpInfo (string accountId, string workspaceId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling WorkspacesApi->WorkspaceGetWorkspace");
            // verify the required parameter 'workspaceId' is set
            if (workspaceId == null)
                throw new ApiException(400, "Missing required parameter 'workspaceId' when calling WorkspacesApi->WorkspaceGetWorkspace");

            var localVarPath = "/v2/accounts/{accountId}/workspaces/{workspaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (workspaceId != null) localVarPathParams.Add("workspaceId", Configuration.ApiClient.ParameterToString(workspaceId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceGetWorkspace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Workspaces>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Workspaces) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Workspaces)));
            
        }

        /// <summary>
        /// Get Workspace Retrives properties about a workspace given a unique workspaceId. 
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Task of Workspaces</returns>
        public async System.Threading.Tasks.Task<Workspaces> WorkspaceGetWorkspaceAsync (string accountId, string workspaceId)
        {
             ApiResponse<Workspaces> localVarResponse = await WorkspaceGetWorkspaceAsyncWithHttpInfo(accountId, workspaceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Workspace Retrives properties about a workspace given a unique workspaceId. 
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <returns>Task of ApiResponse (Workspaces)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Workspaces>> WorkspaceGetWorkspaceAsyncWithHttpInfo (string accountId, string workspaceId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling WorkspacesApi->WorkspaceGetWorkspace");
            // verify the required parameter 'workspaceId' is set
            if (workspaceId == null)
                throw new ApiException(400, "Missing required parameter 'workspaceId' when calling WorkspacesApi->WorkspaceGetWorkspace");

            var localVarPath = "/v2/accounts/{accountId}/workspaces/{workspaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (workspaceId != null) localVarPathParams.Add("workspaceId", Configuration.ApiClient.ParameterToString(workspaceId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceGetWorkspace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Workspaces>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Workspaces) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Workspaces)));
            
        }

        /// <summary>
        /// List Workspaces Gets information about the Workspaces that have been created.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <returns>WorkspaceList</returns>
        public WorkspaceList WorkspaceGetWorkspaces (string accountId)
        {
             ApiResponse<WorkspaceList> localVarResponse = WorkspaceGetWorkspacesWithHttpInfo(accountId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List Workspaces Gets information about the Workspaces that have been created.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <returns>ApiResponse of WorkspaceList</returns>
        public ApiResponse< WorkspaceList > WorkspaceGetWorkspacesWithHttpInfo (string accountId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling WorkspacesApi->WorkspaceGetWorkspaces");

            var localVarPath = "/v2/accounts/{accountId}/workspaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceGetWorkspaces", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WorkspaceList>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (WorkspaceList) Configuration.ApiClient.Deserialize(localVarResponse, typeof(WorkspaceList)));
            
        }

        /// <summary>
        /// List Workspaces Gets information about the Workspaces that have been created.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <returns>Task of WorkspaceList</returns>
        public async System.Threading.Tasks.Task<WorkspaceList> WorkspaceGetWorkspacesAsync (string accountId)
        {
             ApiResponse<WorkspaceList> localVarResponse = await WorkspaceGetWorkspacesAsyncWithHttpInfo(accountId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List Workspaces Gets information about the Workspaces that have been created.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <returns>Task of ApiResponse (WorkspaceList)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<WorkspaceList>> WorkspaceGetWorkspacesAsyncWithHttpInfo (string accountId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling WorkspacesApi->WorkspaceGetWorkspaces");

            var localVarPath = "/v2/accounts/{accountId}/workspaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspaceGetWorkspaces", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WorkspaceList>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (WorkspaceList) Configuration.ApiClient.Deserialize(localVarResponse, typeof(WorkspaceList)));
            
        }

        /// <summary>
        /// Create a Workspace Creates a new workspace.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Workspaces</returns>
        public Workspaces WorkspacePostWorkspace (string accountId, Workspaces workspaces = null)
        {
             ApiResponse<Workspaces> localVarResponse = WorkspacePostWorkspaceWithHttpInfo(accountId, workspaces);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a Workspace Creates a new workspace.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>ApiResponse of Workspaces</returns>
        public ApiResponse< Workspaces > WorkspacePostWorkspaceWithHttpInfo (string accountId, Workspaces workspaces = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling WorkspacesApi->WorkspacePostWorkspace");

            var localVarPath = "/v2/accounts/{accountId}/workspaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (workspaces != null && workspaces.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(workspaces); // http body (model) parameter
            }
            else
            {
                localVarPostBody = workspaces; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspacePostWorkspace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Workspaces>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Workspaces) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Workspaces)));
            
        }

        /// <summary>
        /// Create a Workspace Creates a new workspace.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Task of Workspaces</returns>
        public async System.Threading.Tasks.Task<Workspaces> WorkspacePostWorkspaceAsync (string accountId, Workspaces workspaces = null)
        {
             ApiResponse<Workspaces> localVarResponse = await WorkspacePostWorkspaceAsyncWithHttpInfo(accountId, workspaces);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a Workspace Creates a new workspace.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Task of ApiResponse (Workspaces)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Workspaces>> WorkspacePostWorkspaceAsyncWithHttpInfo (string accountId, Workspaces workspaces = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling WorkspacesApi->WorkspacePostWorkspace");

            var localVarPath = "/v2/accounts/{accountId}/workspaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (workspaces != null && workspaces.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(workspaces); // http body (model) parameter
            }
            else
            {
                localVarPostBody = workspaces; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspacePostWorkspace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Workspaces>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Workspaces) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Workspaces)));
            
        }

        /// <summary>
        /// Update Workspace Updates information about a specific workspace.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Workspaces</returns>
        public Workspaces WorkspacePutWorkspace (string accountId, string workspaceId, Workspaces workspaces = null)
        {
             ApiResponse<Workspaces> localVarResponse = WorkspacePutWorkspaceWithHttpInfo(accountId, workspaceId, workspaces);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update Workspace Updates information about a specific workspace.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>ApiResponse of Workspaces</returns>
        public ApiResponse< Workspaces > WorkspacePutWorkspaceWithHttpInfo (string accountId, string workspaceId, Workspaces workspaces = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling WorkspacesApi->WorkspacePutWorkspace");
            // verify the required parameter 'workspaceId' is set
            if (workspaceId == null)
                throw new ApiException(400, "Missing required parameter 'workspaceId' when calling WorkspacesApi->WorkspacePutWorkspace");

            var localVarPath = "/v2/accounts/{accountId}/workspaces/{workspaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (workspaceId != null) localVarPathParams.Add("workspaceId", Configuration.ApiClient.ParameterToString(workspaceId)); // path parameter
            if (workspaces != null && workspaces.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(workspaces); // http body (model) parameter
            }
            else
            {
                localVarPostBody = workspaces; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspacePutWorkspace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Workspaces>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Workspaces) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Workspaces)));
            
        }

        /// <summary>
        /// Update Workspace Updates information about a specific workspace.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Task of Workspaces</returns>
        public async System.Threading.Tasks.Task<Workspaces> WorkspacePutWorkspaceAsync (string accountId, string workspaceId, Workspaces workspaces = null)
        {
             ApiResponse<Workspaces> localVarResponse = await WorkspacePutWorkspaceAsyncWithHttpInfo(accountId, workspaceId, workspaces);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update Workspace Updates information about a specific workspace.
        /// </summary>
        /// <exception cref="DocuSign.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The external account number (int) or account ID Guid.</param>
        /// <param name="workspaceId">Specifies the workspace ID GUID.</param>
        /// <param name="workspaces"> (optional)</param>
        /// <returns>Task of ApiResponse (Workspaces)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Workspaces>> WorkspacePutWorkspaceAsyncWithHttpInfo (string accountId, string workspaceId, Workspaces workspaces = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling WorkspacesApi->WorkspacePutWorkspace");
            // verify the required parameter 'workspaceId' is set
            if (workspaceId == null)
                throw new ApiException(400, "Missing required parameter 'workspaceId' when calling WorkspacesApi->WorkspacePutWorkspace");

            var localVarPath = "/v2/accounts/{accountId}/workspaces/{workspaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (workspaceId != null) localVarPathParams.Add("workspaceId", Configuration.ApiClient.ParameterToString(workspaceId)); // path parameter
            if (workspaces != null && workspaces.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(workspaces); // http body (model) parameter
            }
            else
            {
                localVarPostBody = workspaces; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WorkspacePutWorkspace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Workspaces>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Workspaces) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Workspaces)));
            
        }

    }
}
